name: No Duplication beyond 3 lines

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: Check duplications
      run: jscpd --format "cpp" . --min-lines 5 --min-tokens 40 --threshold 10
